---
- name: Converge
  hosts: all
  become: true
  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: 600
      changed_when: false
      register: result
      until: result is success
      retries: 5
      delay: 5
    - name: Install iproute2
      apt:
        name: iproute2
        state: present
      changed_when: false
      register: result
      until: result is success
      retries: 5
      delay: 5
    - name: Gather ipv4 address fact again
      setup:
  roles:
    - role: ansible-nut
