---

- name: Install nut
  apt:
    name: nut
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Install NUT configuration files.
  template:
    src: "{{ item }}.j2"
    dest: "/etc/nut/{{ item }}"
    owner: root
    group: nut
    mode: 0640
  with_items:
    - ups.conf
    - upsd.conf
    - upsd.users
    - upsmon.conf
    - nut.conf
  notify: Restart NUT
  become: true
